# Generated by Django 3.1 on 2020-10-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='kind_of_sake',
            new_name='kindSake',
        ),
    ]
