# Generated by Django 3.1 on 2020-10-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20201018_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='sex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
