# Generated by Django 3.1 on 2020-11-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_quiz_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='sex',
            new_name='thirdfeeling',
        ),
    ]
