# Generated by Django 3.1 on 2020-11-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20201106_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='winnner',
            new_name='winner',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='yasaisutelikku',
            new_name='yasaisuteliikku',
        ),
    ]
