# Generated by Django 3.1 on 2020-11-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20201106_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='mediumYyuhi',
            new_name='mediumTyuhi',
        ),
    ]
